# Generated by Django 4.2.23 on 2025-12-04 06:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='ti-folder', help_text='Tabler icon class', max_length=50)),
                ('color', models.CharField(default='#5d87ff', help_text='Hex color for UI', max_length=20)),
                ('category_type', models.CharField(choices=[('fixed', 'Fixed Cost'), ('variable', 'Variable Cost'), ('one_time', 'One-Time')], default='variable', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly budget limit for this category', max_digits=12, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Expense Categories',
                'db_table': 'finance_expense_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(default='ti-wallet', help_text='Tabler icon class', max_length=50)),
                ('color', models.CharField(default='#2ab673', help_text='Hex color for UI', max_length=20)),
                ('source_type', models.CharField(choices=[('enrollment', 'Course Enrollment'), ('event', 'Event/Workshop'), ('sponsorship', 'Sponsorship'), ('partnership', 'Partnership'), ('other', 'Other')], default='other', max_length=20)),
                ('is_auto_imported', models.BooleanField(default=False, help_text='Income is automatically imported from payments system')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Income Categories',
                'db_table': 'finance_income_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('enrollment_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('income_count', models.PositiveIntegerField(default=0)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('expense_count', models.PositiveIntegerField(default=0)),
                ('income_by_category', models.JSONField(default=dict)),
                ('expense_by_category', models.JSONField(default=dict)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('expense_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('income_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expense_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_summaries',
                'ordering': ['-period_start'],
                'unique_together': {('summary_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('partial', 'Partially Received'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('income_date', models.DateField(help_text='Date when income was received/expected')),
                ('is_auto_imported', models.BooleanField(default=False)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/income_receipts/%Y/%m/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='finance.incomecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incomes', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_income_records', to='payments.enrollment')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_income_records', to='payments.payment')),
            ],
            options={
                'db_table': 'finance_incomes',
                'ordering': ['-income_date', '-created_at'],
                'indexes': [models.Index(fields=['income_date'], name='finance_inc_income__9dbaa5_idx'), models.Index(fields=['category'], name='finance_inc_categor_ee2945_idx'), models.Index(fields=['status'], name='finance_inc_status_6b18ed_idx'), models.Index(fields=['is_auto_imported'], name='finance_inc_is_auto_852004_idx'), models.Index(fields=['payment'], name='finance_inc_payment_dee59b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or reference number', max_length=100, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_gstin', models.CharField(blank=True, help_text='GST Number', max_length=20, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expense_date', models.DateField(help_text='Date when expense was incurred')),
                ('payment_date', models.DateField(blank=True, help_text='Date when payment was made', null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_recurring', models.CharField(choices=[('none', 'Non-Recurring'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='finance/receipts/%Y/%m/')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='finance/invoices/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('parent_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='finance.expense')),
            ],
            options={
                'db_table': 'finance_expenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='finance_exp_expense_01b759_idx'), models.Index(fields=['category'], name='finance_exp_categor_7cc816_idx'), models.Index(fields=['status'], name='finance_exp_status_903fdb_idx'), models.Index(fields=['is_recurring'], name='finance_exp_is_recu_9ddd91_idx')],
            },
        ),
    ]
