# Generated by Django 4.2.23 on 2025-12-04 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vendor_type', models.CharField(choices=[('supplier', 'Supplier/Vendor'), ('service_provider', 'Service Provider'), ('employee', 'Employee'), ('customer', 'Customer/Payer'), ('partner', 'Partner/Sponsor'), ('other', 'Other')], default='supplier', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, help_text='GST Number', max_length=20, null=True)),
                ('pan', models.CharField(blank=True, help_text='PAN Number', max_length=15, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_vendors',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='vendor_name',
            field=models.CharField(blank=True, help_text='Or enter vendor name manually', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='payer_name',
            field=models.CharField(blank=True, help_text='Or enter payer name manually', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Select from saved vendors', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.vendor'),
        ),
        migrations.AddField(
            model_name='income',
            name='payer',
            field=models.ForeignKey(blank=True, help_text='Select from saved payers/customers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_records', to='finance.vendor'),
        ),
    ]
