# Generated by Django 5.2.4 on 2025-09-13 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0012_add_video_platform_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Session title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Session description', null=True)),
                ('meeting_link', models.URLField(help_text='Live session meeting link')),
                ('scheduled_date', models.DateTimeField(help_text='When the session is scheduled')),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes')),
                ('assignment_type', models.CharField(choices=[('course', 'Course Students'), ('individual', 'Individual Students'), ('team', 'Team Members'), ('manual', 'Manual Selection')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='Maximum number of participants')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('send_notifications', models.BooleanField(default=True, help_text='Send notifications to participants')),
                ('allow_recording', models.BooleanField(default=False, help_text='Allow session recording')),
                ('is_mandatory', models.BooleanField(default=False, help_text='Mandatory attendance for assigned students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Associated course (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'live_sessions',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('notified', 'Notified'), ('attended', 'Attended'), ('missed', 'Missed'), ('excused', 'Excused')], default='assigned', max_length=20)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Total participation time', null=True)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_rating', models.PositiveIntegerField(blank=True, help_text='Session rating 1-5', null=True)),
                ('feedback_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='live_sessions.livesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_participants',
                'ordering': ['student__name'],
                'unique_together': {('session', 'student')},
            },
        ),
        migrations.CreateModel(
            name='SessionAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('reminder', 'Reminder'), ('update', 'Session Update'), ('cancelled', 'Cancellation'), ('rescheduled', 'Rescheduled')], default='general', max_length=20)),
                ('send_to_all', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_announcements', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='live_sessions.livesession')),
                ('specific_participants', models.ManyToManyField(blank=True, help_text='Leave empty to send to all participants', to='live_sessions.sessionparticipant')),
            ],
            options={
                'db_table': 'session_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_type', models.CharField(choices=[('presentation', 'Presentation'), ('document', 'Document'), ('video', 'Recording'), ('link', 'External Link'), ('assignment', 'Assignment')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='session_resources/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('available_before_session', models.BooleanField(default=True)),
                ('available_during_session', models.BooleanField(default=True)),
                ('available_after_session', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='live_sessions.livesession')),
            ],
            options={
                'db_table': 'session_resources',
                'ordering': ['title'],
            },
        ),
    ]
