# Generated by Django 5.0.1 on 2025-11-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='meeting_link_type',
            field=models.CharField(choices=[('auto', 'Auto (Google Workspace)'), ('manual', 'Manual Entry')], default='auto', help_text='How meeting link is generated', max_length=10),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Live session meeting link (auto-generated or manual)', null=True),
        ),
    ]
