# Generated by Django 5.0.1 on 2025-12-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_add_tuition_fields'),
        ('tuition', '0002_tuitionfaculty_alter_tuitionbatch_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionbatch',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_batches', to='teachers.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='tuitionenrollment',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_tuitions', to='teachers.teacherprofile'),
        ),
    ]
