# Generated by Django 4.2.23 on 2025-12-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0003_add_tuition_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TuitionFaculty',
        ),
    ]
