# Generated by Django 4.2.23 on 2025-12-04 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_online_courses', models.BooleanField(default=True, help_text='Enable online courses, modules, videos, quizzes, assignments, PDF notes')),
                ('enable_live_sessions', models.BooleanField(default=True, help_text='Enable live video sessions/classes')),
                ('enable_online_enrollment', models.BooleanField(default=True, help_text='Enable online course enrollments, student progress tracking')),
                ('enable_certificates', models.BooleanField(default=True, help_text='Enable course completion certificates')),
                ('enable_tuition_management', models.BooleanField(default=False, help_text='Enable offline tuition management - students, batches, attendance, fees')),
                ('enable_finance_management', models.BooleanField(default=False, help_text='Enable expense & income tracking, vendors, financial reports')),
                ('enable_payments', models.BooleanField(default=True, help_text='Enable payment processing, installments, tax invoices')),
                ('enable_assessments', models.BooleanField(default=True, help_text='Enable assignment submissions, quiz attempts, ratings, reviews')),
                ('enable_notifications', models.BooleanField(default=True, help_text='Enable push notifications, email templates')),
                ('enable_website_content', models.BooleanField(default=True, help_text='Enable news, events, testimonials, placements, banners, leads')),
                ('enable_youtube_integration', models.BooleanField(default=False, help_text='Enable YouTube channel sync and video management')),
                ('enable_analytics', models.BooleanField(default=True, help_text='Enable mentor dashboard, student analytics, progress alerts')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feature Configuration',
                'verbose_name_plural': 'Feature Configuration',
            },
        ),
    ]
