# Generated by Django 4.2.23 on 2025-07-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_free_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of module in the course'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of lesson in the module'),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Full YouTube URL (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (optional)', max_length=20, null=True),
        ),
    ]
