# Generated by Django 4.2.23 on 2025-08-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_assignment_quiz_quizquestion_quizchoice_quizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default='Module description not provided.'),
        ),
        migrations.AddField(
            model_name='module',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated completion time', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Module is available to students'),
        ),
        migrations.AddField(
            model_name='module',
            name='learning_objectives',
            field=models.TextField(blank=True, help_text='What students will learn', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum attempts allowed', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='passing_score_percentage',
            field=models.DecimalField(decimal_places=2, default=70.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='module',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Required knowledge or previous modules', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='requires_completion',
            field=models.BooleanField(default=True, help_text='Must complete to progress'),
        ),
        migrations.AddField(
            model_name='module',
            name='resources',
            field=models.TextField(blank=True, help_text='Additional learning resources', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, null=True),
        ),
    ]
