# Generated by Django 5.2.4 on 2025-08-11 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_module_description_module_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
    ]
