# Generated by Django 5.2.4 on 2025-08-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_public_enrollment',
            field=models.BooleanField(default=True, help_text='Allow students to enroll via app/API. If False, only admin can enroll students.'),
        ),
    ]
