# Generated by Django 5.2.4 on 2025-08-27 04:07

from django.db import migrations


def unlock_all_modules(apps, schema_editor):
    """Unlock all existing modules for all students"""
    ModuleProgress = apps.get_model('courses', 'ModuleProgress')
    ModuleProgress.objects.filter(is_unlocked=False).update(is_unlocked=True)


def revert_unlock_modules(apps, schema_editor):
    """Revert to sequential unlocking - only keep first modules unlocked"""
    ModuleProgress = apps.get_model('courses', 'ModuleProgress')
    Module = apps.get_model('courses', 'Module')
    
    # Get all first modules (order=1) for each course
    first_modules = Module.objects.filter(order=1).values_list('id', flat=True)
    
    # Lock all modules except first ones
    ModuleProgress.objects.exclude(module_id__in=first_modules).update(is_unlocked=False)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_allow_public_enrollment'),
    ]

    operations = [
        migrations.RunPython(unlock_all_modules, revert_unlock_modules),
    ]
