# Generated by Django 5.2.4 on 2025-08-27 04:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20250827_0937'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='github_url',
            field=models.URLField(help_text='URL to submission (GitHub, GitLab, Figma, CodePen, Repl.it, CodeSandbox, Vercel, Netlify, or any public URL)'),
        ),
        migrations.CreateModel(
            name='MentorSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('video_call', 'Video Call'), ('phone_call', 'Phone Call'), ('email', 'Email Support'), ('chat', 'Chat Session'), ('in_person', 'In Person')], max_length=15)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Session duration in minutes')),
                ('topics_discussed', models.TextField(help_text='What was discussed in the session')),
                ('action_items', models.TextField(blank=True, help_text='Action items for student', null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('student_satisfaction', models.PositiveIntegerField(blank=True, help_text='1-5 rating from student', null=True)),
                ('mentor_notes', models.TextField(blank=True, null=True)),
                ('session_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='courses.course')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_sessions',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='ProgressAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('inactive', 'Student Inactive'), ('poor_performance', 'Poor Performance'), ('no_submission', 'No Assignment Submissions'), ('quiz_failure', 'Multiple Quiz Failures'), ('course_stalled', 'Course Progress Stalled')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='courses.course')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_login_days', models.PositiveIntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('avg_daily_study_time', models.DurationField(default=datetime.timedelta(0))),
                ('total_videos_watched', models.PositiveIntegerField(default=0)),
                ('total_assignments_submitted', models.PositiveIntegerField(default=0)),
                ('total_quizzes_attempted', models.PositiveIntegerField(default=0)),
                ('avg_quiz_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('avg_assignment_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('courses_completed', models.PositiveIntegerField(default=0)),
                ('modules_completed', models.PositiveIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='low', max_length=10)),
                ('risk_score', models.DecimalField(decimal_places=2, default=0.0, help_text='0-100 risk score', max_digits=5)),
                ('needs_mentoring', models.BooleanField(default=False)),
                ('last_mentor_contact', models.DateTimeField(blank=True, null=True)),
                ('mentoring_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentee_analytics', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Analytics',
                'db_table': 'student_analytics',
            },
        ),
    ]
