# Generated by Django 5.2.4 on 2025-08-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_assignmentsubmission_github_url_mentorsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.TextField(blank=True, help_text='Detailed curriculum outline - what topics will be covered', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, help_text='Learning outcomes - what students will achieve after completing the course', null=True),
        ),
    ]
