# Generated by Django 5.2.4 on 2025-09-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_curriculum_course_what_you_will_learn'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='auto_fetched',
            field=models.BooleanField(default=False, help_text='Was metadata fetched from API?'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='last_api_sync',
            field=models.DateTimeField(blank=True, help_text='Last time metadata was synced', null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='platform',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('direct', 'Direct URL')], default='youtube', help_text='Video platform', max_length=20),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='video_id',
            field=models.CharField(blank=True, help_text='Platform-specific video ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Original video URL', null=True),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='vimeo_video_id',
            field=models.CharField(blank=True, help_text='Vimeo video ID', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Full YouTube URL (legacy)', null=True),
        ),
        migrations.AlterField(
            model_name='videolesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, help_text='YouTube video ID (legacy)', max_length=20, null=True),
        ),
    ]
