# Generated by Django 5.2.4 on 2025-10-08 04:48

import django.db.models.deletion
from django.db import migrations, models


def migrate_existing_data(apps, schema_editor):
    """Migrate existing foreign key relationships to many-to-many through tables"""
    # Get models
    Module = apps.get_model('courses', 'Module')
    CourseModule = apps.get_model('courses', 'CourseModule')
    VideoLesson = apps.get_model('courses', 'VideoLesson')
    ModuleVideo = apps.get_model('courses', 'ModuleVideo')
    Assignment = apps.get_model('courses', 'Assignment')
    ModuleAssignment = apps.get_model('courses', 'ModuleAssignment')
    Quiz = apps.get_model('courses', 'Quiz')
    ModuleQuiz = apps.get_model('courses', 'ModuleQuiz')

    # Migrate Course -> Module relationships
    for module in Module.objects.all():
        if hasattr(module, 'course_id') and module.course_id:
            CourseModule.objects.create(
                course_id=module.course_id,
                module=module,
                order=module.order if hasattr(module, 'order') else 1
            )

    # Migrate Module -> VideoLesson relationships
    for video in VideoLesson.objects.all():
        if hasattr(video, 'module_id') and video.module_id:
            ModuleVideo.objects.create(
                module_id=video.module_id,
                video_lesson=video,
                order=video.order if hasattr(video, 'order') else 1
            )

    # Migrate Module -> Assignment relationships
    for assignment in Assignment.objects.all():
        if hasattr(assignment, 'module_id') and assignment.module_id:
            ModuleAssignment.objects.create(
                module_id=assignment.module_id,
                assignment=assignment,
                order=assignment.order if hasattr(assignment, 'order') else 1
            )

    # Migrate Module -> Quiz relationships
    for quiz in Quiz.objects.all():
        if hasattr(quiz, 'module_id') and quiz.module_id:
            ModuleQuiz.objects.create(
                module_id=quiz.module_id,
                quiz=quiz,
                order=quiz.order if hasattr(quiz, 'order') else 1
            )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_video_platform_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='videolesson',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='module',
        ),
        migrations.RemoveField(
            model_name='videolesson',
            name='order',
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of module in this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='courses.module')),
            ],
            options={
                'db_table': 'course_modules',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'module')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='modules',
            field=models.ManyToManyField(related_name='module_courses', through='courses.CourseModule', to='courses.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(related_name='course_modules', through='courses.CourseModule', to='courses.course'),
        ),
        migrations.CreateModel(
            name='ModuleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of assignment in this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='courses.assignment')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_links', to='courses.module')),
            ],
            options={
                'db_table': 'module_assignments',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'assignment')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='modules',
            field=models.ManyToManyField(related_name='module_assignments', through='courses.ModuleAssignment', to='courses.module'),
        ),
        migrations.CreateModel(
            name='ModuleQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of quiz in this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='courses.module')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='courses.quiz')),
            ],
            options={
                'db_table': 'module_quizzes',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'quiz')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='modules',
            field=models.ManyToManyField(related_name='module_quizzes', through='courses.ModuleQuiz', to='courses.module'),
        ),
        migrations.CreateModel(
            name='ModuleVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of video in this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='courses.module')),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='courses.videolesson')),
            ],
            options={
                'db_table': 'module_videos',
                'ordering': ['module', 'order'],
                'unique_together': {('module', 'video_lesson')},
            },
        ),
        migrations.AddField(
            model_name='videolesson',
            name='modules',
            field=models.ManyToManyField(related_name='module_videos', through='courses.ModuleVideo', to='courses.module'),
        ),
        # Migrate existing data before removing old fields
        migrations.RunPython(migrate_existing_data, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='assignment',
            name='module',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='module',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='order',
        ),
    ]
