# Generated by Django 5.0.1 on 2025-11-12 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_refactor_to_many_to_many'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_days',
            field=models.PositiveIntegerField(default=7, help_text='Days from start to complete assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Required to proceed'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='module_assignments', through='courses.ModuleAssignment', to='courses.module'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Required to proceed'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='modules',
            field=models.ManyToManyField(blank=True, related_name='module_quizzes', through='courses.ModuleQuiz', to='courses.module'),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of assignment in this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='courses.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_links', to='courses.course')),
            ],
            options={
                'db_table': 'course_assignments',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'assignment')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_assignments', through='courses.CourseAssignment', to='courses.course'),
        ),
        migrations.CreateModel(
            name='CoursePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of PDF in this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_links', to='courses.course')),
            ],
            options={
                'db_table': 'course_pdfs',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of quiz in this course')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='courses.course')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='courses.quiz')),
            ],
            options={
                'db_table': 'course_quizzes',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'quiz')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='course_quizzes', through='courses.CourseQuiz', to='courses.course'),
        ),
        migrations.CreateModel(
            name='ModulePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of PDF in this module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_links', to='courses.module')),
            ],
            options={
                'db_table': 'module_pdfs',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PDFNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the PDF content', null=True)),
                ('pdf_file', models.FileField(help_text='Upload PDF file', upload_to='course_pdfs/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('page_count', models.PositiveIntegerField(blank=True, help_text='Number of pages', null=True)),
                ('is_downloadable', models.BooleanField(default=True, help_text='Allow students to download')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='course_pdfs', through='courses.CoursePDF', to='courses.course')),
                ('modules', models.ManyToManyField(blank=True, related_name='module_pdfs', through='courses.ModulePDF', to='courses.module')),
            ],
            options={
                'db_table': 'pdf_notes',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='modulepdf',
            name='pdf_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_links', to='courses.pdfnote'),
        ),
        migrations.AddField(
            model_name='coursepdf',
            name='pdf_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_links', to='courses.pdfnote'),
        ),
        migrations.CreateModel(
            name='VideoAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of assignment for this video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='courses.assignment')),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_links', to='courses.videolesson')),
            ],
            options={
                'db_table': 'video_assignments',
                'ordering': ['video_lesson', 'order'],
                'unique_together': {('video_lesson', 'assignment')},
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='video_lessons',
            field=models.ManyToManyField(blank=True, related_name='video_assignments', through='courses.VideoAssignment', to='courses.videolesson'),
        ),
        migrations.CreateModel(
            name='VideoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of PDF for this video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='courses.pdfnote')),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_links', to='courses.videolesson')),
            ],
            options={
                'db_table': 'video_pdfs',
                'ordering': ['video_lesson', 'order'],
                'unique_together': {('video_lesson', 'pdf_note')},
            },
        ),
        migrations.AddField(
            model_name='pdfnote',
            name='video_lessons',
            field=models.ManyToManyField(blank=True, related_name='video_pdfs', through='courses.VideoPDF', to='courses.videolesson'),
        ),
        migrations.CreateModel(
            name='VideoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of quiz for this video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='courses.quiz')),
                ('video_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_links', to='courses.videolesson')),
            ],
            options={
                'db_table': 'video_quizzes',
                'ordering': ['video_lesson', 'order'],
                'unique_together': {('video_lesson', 'quiz')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='video_lessons',
            field=models.ManyToManyField(blank=True, related_name='video_quizzes', through='courses.VideoQuiz', to='courses.videolesson'),
        ),
        migrations.AlterUniqueTogether(
            name='modulepdf',
            unique_together={('module', 'pdf_note')},
        ),
        migrations.AlterUniqueTogether(
            name='coursepdf',
            unique_together={('course', 'pdf_note')},
        ),
    ]
