# Generated by Django 4.2.23 on 2025-12-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_add_multi_level_content_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch_info',
            field=models.CharField(blank=True, help_text="e.g., 'Weekend Batch', 'Weekday Evening'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g., '6 months', '12 weeks'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_type',
            field=models.CharField(choices=[('online_purchase', 'Online Purchase'), ('admin_only', 'Admin Enrollment Only'), ('enquiry_only', 'Enquiry Only')], default='online_purchase', help_text='How students can enroll in this course', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, help_text='Next batch start date', null=True),
        ),
    ]
