# Generated by Django 4.2.23 on 2025-12-03 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0008_payment_razorpay_order_id_and_more'),
        ('courses', '0015_course_batch_info_course_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_type', models.CharField(choices=[('completion', 'Course Completion'), ('excellence', 'Excellence Award'), ('participation', 'Participation')], default='completion', max_length=20)),
                ('title', models.CharField(help_text="Title displayed on certificate (e.g., 'Certificate of Completion')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Additional text to display on certificate', null=True)),
                ('completion_date', models.DateField(help_text='Date when course was completed')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score percentage (if applicable)', max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, help_text='Grade (e.g., A+, A, B+, etc.)', max_length=10, null=True)),
                ('verification_code', models.CharField(help_text='Unique code for certificate verification', max_length=100, unique=True)),
                ('verification_url', models.URLField(blank=True, help_text='Full URL for certificate verification', null=True)),
                ('pdf_file', models.FileField(blank=True, help_text='Generated PDF certificate', null=True, upload_to='certificates/')),
                ('is_revoked', models.BooleanField(default=False, help_text='Set to True if certificate is revoked')),
                ('revoked_reason', models.TextField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, help_text='Name of person who signed the certificate', max_length=200, null=True)),
                ('signed_by_title', models.CharField(blank=True, help_text="Title of person who signed (e.g., 'Director of Training')", max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='payments.enrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates',
                'ordering': ['-issue_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
