# Generated by Django 4.2.23 on 2025-12-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_add_certificate_model'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together=set(),
        ),
    ]
