# Generated by Django 4.2.23 on 2025-12-04 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0017_remove_certificate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current consecutive days streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest streak ever achieved')),
                ('total_active_days', models.PositiveIntegerField(default=0, help_text='Total days with learning activity')),
                ('streak_start_date', models.DateField(blank=True, help_text='Start date of current streak', null=True)),
                ('last_activity_date', models.DateField(blank=True, help_text='Last date with activity', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Streak',
                'verbose_name_plural': 'Daily Streaks',
                'db_table': 'daily_streaks',
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activities_count', models.PositiveIntegerField(default=0, help_text='Total activities on this day')),
                ('videos_watched', models.PositiveIntegerField(default=0)),
                ('quizzes_attempted', models.PositiveIntegerField(default=0)),
                ('assignments_submitted', models.PositiveIntegerField(default=0)),
                ('learning_minutes', models.PositiveIntegerField(default=0, help_text='Total learning time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Activity',
                'verbose_name_plural': 'Daily Activities',
                'db_table': 'daily_activities',
                'ordering': ['-activity_date'],
                'unique_together': {('student', 'activity_date')},
            },
        ),
    ]
