# Generated by Django 4.2.23 on 2025-12-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_add_tuition_fields'),
        ('courses', '0018_add_daily_streak_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Primary teacher/instructor for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to='teachers.teacherprofile'),
        ),
    ]
