# Generated by Django 4.2.23 on 2025-07-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_enrollment_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='installment_plan',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='has_installment_plan',
            field=models.BooleanField(default=False, help_text='Whether this enrollment has an installment plan'),
        ),
        migrations.AddField(
            model_name='installmentplan',
            name='enrollment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installment_plan_details', to='payments.enrollment'),
        ),
    ]
