# Generated by Django 4.2.23 on 2025-07-31 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_teammembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_remove_enrollment_installment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team for team enrollments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.team'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('team', 'Team'), ('admin_assigned', 'Admin Assigned')], default='individual', max_length=15),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(help_text='Primary student (for individual) or team representative', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
