# Generated by Django 5.2.4 on 2025-08-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_enrollment_team_alter_enrollment_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount including tax', max_digits=10),
        ),
    ]
