# Generated by Django 4.2.23 on 2025-12-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_remove_tuition_faculty'),
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Parent/Guardian email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_name',
            field=models.CharField(blank=True, help_text='Parent/Guardian name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Parent/Guardian phone', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, help_text='Student profile photo', null=True, upload_to='students/photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='school_name',
            field=models.CharField(blank=True, help_text='School/College name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='standard',
            field=models.ForeignKey(blank=True, help_text='Class/Standard for tuition students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_students', to='tuition.standard'),
        ),
        migrations.AddField(
            model_name='user',
            name='student_type',
            field=models.CharField(choices=[('online', 'Online Only'), ('offline', 'Offline/Tuition Only'), ('both', 'Both Online & Offline')], default='online', help_text='Type of student: online courses, offline tuition, or both', max_length=10),
        ),
    ]
