# Generated by Django 5.2.4 on 2025-09-07 08:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('area_of_interest', models.CharField(choices=[('web_development', 'Web Development'), ('mobile_development', 'Mobile Development'), ('data_science', 'Data Science'), ('ai_ml', 'AI/Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('cloud_computing', 'Cloud Computing'), ('devops', 'DevOps'), ('other', 'Other')], max_length=50)),
                ('other_interest', models.CharField(blank=True, help_text="If 'Other' is selected", max_length=100, null=True)),
                ('current_experience', models.CharField(choices=[('beginner', 'Complete Beginner'), ('some_knowledge', 'Some Knowledge'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Working Professional')], max_length=50)),
                ('career_goals', models.TextField(help_text='What are your career goals?')),
                ('learning_timeline', models.CharField(help_text='When do you want to achieve your goals?', max_length=200)),
                ('budget_range', models.CharField(blank=True, help_text='Budget expectations', max_length=100, null=True)),
                ('preferred_time', models.CharField(help_text='Preferred time for session', max_length=100)),
                ('specific_topics', models.TextField(blank=True, help_text='Any specific topics to discuss?', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Session Scheduled'), ('completed', 'Session Completed'), ('not_interested', 'Not Interested'), ('converted', 'Converted to Student')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='mobile_app', help_text='Where did the lead come from?', max_length=50)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('call', 'Phone Call'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('meeting', 'Meeting'), ('demo', 'Demo Session')], max_length=20)),
                ('notes', models.TextField()),
                ('scheduled_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='content_management.lead')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(help_text='Brief summary for cards/lists', max_length=300)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/thumbnails/')),
                ('category', models.CharField(choices=[('general', 'General News'), ('course_update', 'Course Updates'), ('industry_news', 'Industry News'), ('company_news', 'Company News'), ('event', 'Events'), ('announcement', 'Announcements')], default='general', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage/featured section')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='placements/photos/')),
                ('course_completed', models.CharField(max_length=100)),
                ('batch_year', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=100)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='placements/logos/')),
                ('job_title', models.CharField(max_length=100)),
                ('placement_type', models.CharField(choices=[('full_time', 'Full Time Job'), ('internship', 'Internship'), ('freelance', 'Freelance Project'), ('startup', 'Started Own Company'), ('promotion', 'Job Promotion')], max_length=20)),
                ('package_amount', models.DecimalField(decimal_places=2, help_text='Annual package in currency', max_digits=10)),
                ('package_currency', models.CharField(default='INR', max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('success_story', models.TextField(help_text="Student's journey and success story")),
                ('key_achievements', models.JSONField(default=list, help_text='List of key achievements')),
                ('skills_gained', models.TextField(help_text='Skills learned during the course')),
                ('technologies_used', models.CharField(help_text='Technologies used in current role', max_length=300)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Student consent to publish details')),
                ('can_show_package', models.BooleanField(default=True, help_text='Can show package details publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/')),
                ('course_name', models.CharField(max_length=100)),
                ('batch_year', models.CharField(max_length=10)),
                ('testimonial_type', models.CharField(choices=[('video_youtube', 'YouTube Video'), ('text_image', 'Text + Image'), ('video_upload', 'Uploaded Video'), ('audio', 'Audio Recording')], max_length=20)),
                ('testimonial_text', models.TextField(blank=True, help_text='Written testimonial content', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video URL', null=True, validators=[django.core.validators.URLValidator()])),
                ('youtube_video_id', models.CharField(blank=True, help_text='Extracted YouTube video ID', max_length=20, null=True)),
                ('uploaded_video', models.FileField(blank=True, null=True, upload_to='testimonials/videos/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='testimonials/thumbnails/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='testimonials/audio/')),
                ('overall_rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('course_rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('instructor_rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('key_learnings', models.TextField(blank=True, help_text='What did they learn?', null=True)),
                ('career_impact', models.TextField(blank=True, help_text='How did it impact their career?', null=True)),
                ('recommendation', models.TextField(blank=True, help_text='Would they recommend? Why?', null=True)),
                ('current_position', models.CharField(blank=True, max_length=100, null=True)),
                ('current_company', models.CharField(blank=True, max_length=100, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured testimonials')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Student consent to publish')),
                ('can_show_details', models.BooleanField(default=True, help_text='Can show personal details')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('shares_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='content_man_status_11b76a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['area_of_interest'], name='content_man_area_of_e40652_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='content_man_created_04d7fb_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published', 'published_at'], name='content_man_is_publ_0a0669_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category'], name='content_man_categor_41a5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_featured'], name='content_man_is_feat_dc0b88_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['is_published', 'published_at'], name='content_man_is_publ_fe97c9_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['is_featured'], name='content_man_is_feat_94a986_idx'),
        ),
        migrations.AddIndex(
            model_name='placement',
            index=models.Index(fields=['placement_type'], name='content_man_placeme_16955c_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_published', 'published_at'], name='content_man_is_publ_739bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['is_featured'], name='content_man_is_feat_4c4c92_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['testimonial_type'], name='content_man_testimo_a1fda8_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonial',
            index=models.Index(fields=['overall_rating'], name='content_man_overall_8bac51_idx'),
        ),
    ]
