# Generated by Django 5.2.4 on 2025-09-10 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this lead (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
