# Generated by Django 4.2.23 on 2025-12-03 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_management', '0002_lead_submitted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief summary for cards/lists', max_length=300)),
                ('event_type', models.CharField(choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('hackathon', 'Hackathon'), ('meetup', 'Meetup'), ('conference', 'Conference'), ('open_day', 'Open Day'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='upcoming', max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('is_online', models.BooleanField(default=True)),
                ('venue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('venue_address', models.TextField(blank=True, null=True)),
                ('map_link', models.URLField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, help_text='Zoom/Meet/Teams link', null=True)),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/')),
                ('registration_required', models.BooleanField(default=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('max_attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('speakers', models.TextField(blank=True, help_text='Speaker names and details (comma-separated or JSON)', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
                'indexes': [models.Index(fields=['is_published', 'event_date'], name='content_man_is_publ_21e858_idx'), models.Index(fields=['status'], name='content_man_status_ff30d7_idx'), models.Index(fields=['is_featured'], name='content_man_is_feat_c1a8ef_idx'), models.Index(fields=['event_type'], name='content_man_event_t_849af0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading text', max_length=100)),
                ('subtitle', models.CharField(blank=True, help_text='Secondary heading text', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Supporting text/description', null=True)),
                ('cta_text', models.CharField(blank=True, help_text="Button text (e.g., 'Explore Courses')", max_length=50, null=True)),
                ('cta_link', models.CharField(blank=True, help_text='Button link URL or path', max_length=200, null=True)),
                ('secondary_cta_text', models.CharField(blank=True, help_text='Secondary button text', max_length=50, null=True)),
                ('secondary_cta_link', models.CharField(blank=True, help_text='Secondary button link', max_length=200, null=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='banners/backgrounds/')),
                ('featured_image', models.ImageField(blank=True, help_text='Image displayed on the right side', null=True, upload_to='banners/featured/')),
                ('banner_type', models.CharField(choices=[('hero', 'Main Hero Banner'), ('promo', 'Promotional Banner'), ('announcement', 'Announcement Banner'), ('seasonal', 'Seasonal/Holiday Banner')], default='hero', max_length=20)),
                ('text_color', models.CharField(default='white', help_text="Text color (e.g., 'white', '#ffffff')", max_length=20)),
                ('overlay_opacity', models.DecimalField(decimal_places=2, default=0.5, help_text='Background overlay opacity (0-1)', max_digits=3)),
                ('stat_1_value', models.CharField(blank=True, help_text="e.g., '500+'", max_length=20, null=True)),
                ('stat_1_label', models.CharField(blank=True, help_text="e.g., 'Students Enrolled'", max_length=50, null=True)),
                ('stat_2_value', models.CharField(blank=True, max_length=20, null=True)),
                ('stat_2_label', models.CharField(blank=True, max_length=50, null=True)),
                ('stat_3_value', models.CharField(blank=True, max_length=20, null=True)),
                ('stat_3_label', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='When to start showing this banner', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing this banner', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority banners show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'banner_type'], name='content_man_is_acti_55e3e4_idx'), models.Index(fields=['priority'], name='content_man_priorit_4efac6_idx')],
            },
        ),
    ]
