# Generated by Django 4.2.23 on 2025-12-03 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content_management', '0003_event_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief summary for cards/lists', max_length=300)),
                ('achievement_type', models.CharField(choices=[('award', 'Award'), ('recognition', 'Recognition'), ('milestone', 'Milestone'), ('partnership', 'Partnership'), ('accreditation', 'Accreditation'), ('ranking', 'Ranking')], max_length=20)),
                ('awarded_by', models.CharField(help_text='Organization that gave the award/recognition', max_length=200)),
                ('achievement_date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/images/')),
                ('badge_icon', models.ImageField(blank=True, null=True, upload_to='achievements/badges/')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='achievements/certificates/')),
                ('year', models.CharField(max_length=4)),
                ('category', models.CharField(blank=True, help_text="e.g., 'Education', 'Technology'", max_length=100, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achievement_date', '-created_at'],
                'indexes': [models.Index(fields=['is_published'], name='content_man_is_publ_6e6761_idx'), models.Index(fields=['is_featured'], name='content_man_is_feat_1f951b_idx'), models.Index(fields=['achievement_type'], name='content_man_achieve_23d8d3_idx')],
            },
        ),
    ]
