# Generated by Django 4.2.23 on 2025-12-03 08:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0015_course_batch_info_course_duration_and_more'),
        ('content_management', '0004_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')])),
                ('message', models.TextField(blank=True, help_text="User's message or query", null=True)),
                ('preferred_batch', models.CharField(blank=True, help_text='Preferred batch timing', max_length=100, null=True)),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100, null=True)),
                ('current_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('demo_scheduled', 'Demo Scheduled'), ('enrolled', 'Enrolled'), ('not_interested', 'Not Interested'), ('follow_up', 'Follow Up Required')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('google_ads', 'Google Ads'), ('other', 'Other')], default='website', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_course_enquiries', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='courses.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Course Enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='content_man_status_180f2b_idx'), models.Index(fields=['course'], name='content_man_course__5440a2_idx'), models.Index(fields=['created_at'], name='content_man_created_e9508f_idx')],
            },
        ),
    ]
