# Generated by Django 5.0.1 on 2025-12-17 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0005_courseenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenquiry',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{9,15}$', 'Enter a valid phone number (9-15 digits, optional + prefix).')]),
        ),
    ]
