# Generated by Django 4.2.23 on 2025-12-05 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0018_add_daily_streak_models'),
        ('tuition', '0002_tuitionfaculty_alter_tuitionbatch_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text='Unique employee identifier', max_length=50, null=True, unique=True)),
                ('designation', models.CharField(blank=True, help_text='e.g., Senior Instructor, Professor', max_length=100, null=True)),
                ('department', models.CharField(blank=True, help_text='Subject area/department', max_length=100, null=True)),
                ('qualification', models.TextField(blank=True, help_text='Educational qualifications', null=True)),
                ('specialization', models.TextField(blank=True, help_text='Areas of expertise', null=True)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of teaching experience')),
                ('bio', models.TextField(blank=True, help_text='Short biography', null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='teacher_photos/')),
                ('date_of_joining', models.DateField(blank=True, help_text='Employment start date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=True, help_text='Force password change on first login')),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_courses', models.ManyToManyField(blank=True, help_text='Courses assigned to this teacher', related_name='assigned_teachers', to='courses.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teacher_profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedules', to='tuition.tuitionbatch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schedules', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='teachers.teacherprofile')),
            ],
            options={
                'db_table': 'teacher_schedules',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_global', models.BooleanField(default=False, help_text="Visible to all teacher's students")),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for all courses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_announcements', to='courses.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='teachers.teacherprofile')),
            ],
            options={
                'db_table': 'teacher_announcements',
                'ordering': ['-publish_at'],
            },
        ),
    ]
