# Generated by Django 5.0.1 on 2025-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_add_daily_streak_models'),
        ('teachers', '0001_initial'),
        ('tuition', '0002_tuitionfaculty_alter_tuitionbatch_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Residential address', null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate contact number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='can_teach_offline',
            field=models.BooleanField(default=True, help_text='Can teach offline tuition batches'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='can_teach_online',
            field=models.BooleanField(default=True, help_text='Can teach online courses'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the teacher', null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tuition_subjects',
            field=models.ManyToManyField(blank=True, help_text='Offline tuition subjects this teacher can teach', related_name='teachers', to='tuition.subject'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='assigned_courses',
            field=models.ManyToManyField(blank=True, help_text='Online courses assigned to this teacher', related_name='assigned_teachers', to='courses.course'),
        ),
    ]
