# Generated by Django 5.0.1 on 2025-11-12 11:48

import django.db.models.deletion
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMeetSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(help_text='Google Calendar event ID', max_length=255, unique=True)),
                ('google_meet_code', models.CharField(help_text='Meeting code (e.g., abc-defg-hij)', max_length=50)),
                ('calendar_link', models.URLField(help_text='Link to Google Calendar event')),
                ('hangout_link', models.URLField(help_text='Google Meet join link')),
                ('recording_enabled', models.BooleanField(default=False, help_text='Whether recording is enabled for this meeting')),
                ('waiting_room_enabled', models.BooleanField(default=True, help_text='Whether waiting room is enabled')),
                ('recording_urls', models.JSONField(blank=True, default=list, help_text='List of recording URLs (if any)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_google_meets', to=settings.AUTH_USER_MODEL)),
                ('live_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_meet_info', to='live_sessions.livesession')),
            ],
            options={
                'verbose_name': 'Google Meet Session',
                'verbose_name_plural': 'Google Meet Sessions',
                'db_table': 'google_meet_sessions',
            },
        ),
        migrations.CreateModel(
            name='GoogleWorkspaceIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_email', models.EmailField(help_text='Google Workspace email address', max_length=254)),
                ('access_token', encrypted_model_fields.fields.EncryptedTextField(help_text='OAuth access token (encrypted)')),
                ('refresh_token', encrypted_model_fields.fields.EncryptedTextField(help_text='OAuth refresh token (encrypted)')),
                ('token_expires_at', models.DateTimeField(help_text='When the access token expires')),
                ('scopes', models.JSONField(default=list, help_text='List of granted OAuth scopes')),
                ('is_active', models.BooleanField(default=True, help_text='If false, integration is disabled')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('admin_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Workspace Integration',
                'verbose_name_plural': 'Google Workspace Integrations',
                'db_table': 'google_workspace_integrations',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key (e.g., RAZORPAY_KEY_ID)', max_length=255, unique=True)),
                ('value', encrypted_model_fields.fields.EncryptedTextField(help_text='Encrypted value of the setting')),
                ('category', models.CharField(choices=[('email', 'Email Settings'), ('payment', 'Payment Gateway'), ('google', 'Google Services'), ('firebase', 'Firebase/FCM'), ('storage', 'Storage (AWS/S3)'), ('sms', 'SMS Service'), ('security', 'Security'), ('general', 'General Settings')], help_text='Category of the setting', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting is for')),
                ('is_sensitive', models.BooleanField(default=True, help_text='If true, value will be masked in admin UI')),
                ('is_active', models.BooleanField(default=True, help_text='If false, system will fall back to environment variable')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SettingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_value', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('new_value', encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('change_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='system_settings.systemsetting')),
            ],
            options={
                'verbose_name': 'Setting Change Log',
                'verbose_name_plural': 'Setting Change Logs',
                'db_table': 'setting_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
