# Generated by Django 5.2.4 on 2025-09-16 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_userdevice_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdevice',
            name='unique_user_device',
        ),
        migrations.RemoveConstraint(
            model_name='userdevice',
            name='unique_anonymous_device',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='push_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='push_status',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_due', 'Payment Due'), ('payment_received', 'Payment Received'), ('course_assigned', 'Course Assigned'), ('course_completed', 'Course Completed'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('system_alert', 'System Alert')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_token')},
        ),
    ]
