# Generated by Django 5.2.4 on 2025-09-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_userdevice_unique_user_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='push_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='push_status',
            field=models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('payment_due', 'Payment Due'), ('payment_received', 'Payment Received'), ('course_assigned', 'Course Assigned'), ('course_completed', 'Course Completed'), ('enrollment_confirmed', 'Enrollment Confirmed'), ('system_alert', 'System Alert'), ('session_assigned', 'Session Assigned'), ('session_started', 'Session Started'), ('session_reminder', 'Session Reminder'), ('session_cancelled', 'Session Cancelled'), ('session_announcement', 'Session Announcement')], max_length=20),
        ),
    ]
